let stockProductos = [
    {id: 1, nombre: "Caqui", tipo: "Fruta", cantidad: 1, desc: "caja de moras 250g", precio: 2.50, talle: "L", img: './img.index/caquis.png'},
    {id: 2, nombre: "Cereza", tipo: "Fruta", cantidad: 1, desc: "Un buzo que re va con vos", precio: 1100, talle: "L", img: './img.index/cerezas.png'},
    {id: 3, nombre: "ciruela", tipo: "Fruta", cantidad: 1, desc: "Un buzo que re va con vos", precio: 1200, talle: "M", img: './img.index/ciruelas.png'},
    {id: 4, nombre: "Coco", tipo: "Fruta", cantidad: 1, desc: "Un buzo que re va con vos", precio: 1400, talle: "M", img: './img.index/cocos.png'},
    {id: 5, nombre: "Frambuesa", tipo: "Fruta", cantidad: 1, desc: "Un buzo que re va con vos", precio: 1200, talle: "S", img: './img.index/frambuesas.png'},
    {id: 6, nombre: "Fresa", tipo: "Fruta", cantidad: 1, desc: "Un buzo que re va con vos", precio: 1500, talle: "S", img: './img.index/fresas.png'},
    {id: 7, nombre: "Fruta de la Pasion", tipo: "Fruta", cantidad: 1, desc: "Una remera que re va con vos", precio: 500, talle: "L", img: './img.index/frutadelapasion.png'},
    {id: 8, nombre: "Granada", tipo: "Fruta", cantidad: 1, desc: "Una remera que re va con vos", precio: 500, talle: "L", img: './img.index/granada.png'},
    {id: 9, nombre: "Higos", tipo: "Fruta", cantidad: 1, desc: "Una remera que re va con vos", precio: 500, talle: "M", img: './img.index/higos.png'},
    {id: 10, nombre: "Kiwi", tipo: "Fruta", cantidad: 1, desc: "Una remera que re va con vos", precio: 700, talle: "M", img: './img.index/kiwi.png'},
    {id: 11, nombre: "Limon", tipo: "Fruta", cantidad: 1,desc: "Una remera que re va con vos", precio: 700, talle: "S", img: './img.index/limones.png'},
    {id: 12, nombre: "Manzana", tipo: "Fruta", cantidad: 1, desc: "Una remera que re va con vos", precio: 700, talle: "S", img: './img.index/manzana.png'},
    {id: 13, nombre: "Melocoton", tipo: "Fruta", cantidad: 1, desc: "Una camisa que re va con vos", precio: 900, talle: "L", img: './img.index/melocotones.png'},
    {id: 14, nombre: "Melon", tipo: "Fruta", cantidad: 1, desc: "Una camisa que re va con vos", precio: 1400, talle: "S", img: './img.index/melones.png'},
    {id: 15, nombre: "Mora", tipo: "Fruta", cantidad: 1, desc: "Una camisa que re va con vos", precio: 7000, talle: "L", img: './img.index/moras.png'},
    {id: 16, nombre: "Naranja", tipo: "Fruta", cantidad: 1, desc: "Una camisa que re va con vos", precio: 777, talle: "S", img: './img.index/naranjas.png'},
    {id: 17, nombre: "Papaya", tipo: "Fruta", cantidad: 1, desc: "Una camisa que re va con vos", precio: 234, talle: "S", img: './img.index/papayas.png'},
    {id: 18, nombre: "Pera", tipo: "Fruta", cantidad: 1, desc: "Una camisa que re va con vos", precio: 155600, talle: "M", img: './img.index/peras.png'},
    {id: 19, nombre: "Pinia", tipo: "Fruta", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 1600, talle: "L", img: './img.index/pinias.png'},
    {id: 20, nombre: "Platano", tipo: "Fruta", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 3200, talle: "L", img: './img.index/platano.png'},
    {id: 21, nombre: "Sandia", tipo: "Fruta", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 2300, talle: "M", img: './img.index/sandias.png'},
    {id: 22, nombre: "Uva", tipo: "Fruta", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 5600, talle: "M", img: './img.index/uvas.png'},
    {id: 23, nombre: "Ajos", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 1700, talle: "S", img: './'},
    {id: 24, nombre: "Alcachofa", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 800, talle: "S", img: './'},
    {id: 24, nombre: "Brenjena", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 1700, talle: "S", img: './'},
    {id: 25, nombre: "Brocoli", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 800, talle: "S", img: './'},
    {id: 26, nombre: "Calabacin", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 1700, talle: "S", img: './'},
    {id: 27, nombre: "Calabaza", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 800, talle: "S", img: './'},
    {id: 28, nombre: "Coliflor", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 800, talle: "S", img: './'},
    {id: 29, nombre: "Coliflor", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 800, talle: "S", img: './'},
    {id: 30, nombre: "Espinaca", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 1700, talle: "S", img: './'},
    {id: 31, nombre: "Guisante", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 800, talle: "S", img: './'},
    {id: 32, nombre: "Haba", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 1700, talle: "S", img: './'},
    {id: 33, nombre: "Judias Verdes", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 800, talle: "S", img: './'},
    {id: 34, nombre: "Lechuga", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 1700, talle: "S", img: './'},
    {id: 35, nombre: "Maiz", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 800, talle: "S", img: './'},
    {id: 36, nombre: "Patata", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 1700, talle: "S", img: './'},
    {id: 37, nombre: "Pepino", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 800, talle: "S", img: './'},
    {id: 38, nombre: "Pimiento", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 1700, talle: "S", img: './'},
    {id: 39, nombre: "Puerro", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 800, talle: "S", img: './'},
    {id: 40, nombre: "Remolacha", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 1700, talle: "S", img: './'},
    {id: 41, nombre: "Tomate", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 800, talle: "S", img: './'},
    {id: 42, nombre: "Zanahoria", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 1700, talle: "S", img: './'},
    {id: 43, nombre: "", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 1700, talle: "S", img: './'},
    {id: 44, nombre: "", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 800, talle: "S", img: './'},
    {id: 45, nombre: "", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 1700, talle: "S", img: './'},
    {id: 46, nombre: "", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 800, talle: "S", img: './'},
    {id: 47, nombre: "", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 1700, talle: "S", img: './'},
    {id: 48, nombre: "", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 800, talle: "S", img: './'},
    {id: 49, nombre: "", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 1700, talle: "S", img: './'},
    {id: 50, nombre: "", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 800, talle: "S", img: './'},
    {id: 51, nombre: "", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 1700, talle: "S", img: './'},
    {id: 52, nombre: "", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 800, talle: "S", img: './'},
    {id: 53, nombre: "", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 1700, talle: "S", img: './'},
    {id: 54, nombre: "", tipo: "", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 800, talle: "S", img: './'},

]
